name = "Betch"
license = "MIT"
licenselink = "https://github.com/synalice/betch/blob/main/LICENSE"
description = "An improved etch theme for Hugo."
homepage = "https://github.com/synalice/betch/"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive"]
features = ["fast", "blog", "syntax highlighting"]
min_version = "0.1.0"

[author]
  name = "Nikita (synalice) Krasnov"
  homepage = "https://github.com/synalice/"

# If porting an existing theme
[original]
  name = "etch"
  homepage = "https://github.com/LukasJoswiak/etch/"
  repo = "https://github.com/LukasJoswiak/etch/"
